import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faAngleDown,
  faAngleRight,
  faAddressCard,
  faBullhorn,
  faCalculator,
  faCaretUp,
  faCaretDown,
  faCheck,
  faChevronLeft,
  faCloudDownloadAlt,
  faCreditCard,
  faCubes,
  faDollarSign,
  faEdit,
  faFileAlt,
  faFileInvoice,
  faFileInvoiceDollar,
  faGlobeAsia,
  faImage,
  faInfo,
  faInfoCircle,
  faMap,
  faPenAlt,
  faPlus,
  faPrint,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faShippingFast,
  faSpinner,
  faStar,
  faTags,
  faTimes,
  faTrashAlt,
  faTruck,
  faUser,
  faWallet,
  faWarehouse
} from '@fortawesome/free-solid-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add([
  faAngleDown,
  faAngleRight,
  faAddressCard,
  faBullhorn,
  faCalculator,
  faCaretUp,
  faCaretDown,
  faCheck,
  faChevronLeft,
  faCloudDownloadAlt,
  faCreditCard,
  faCubes,
  faDollarSign,
  faEdit,
  faFileAlt,
  faFileInvoice,
  faFileInvoiceDollar,
  faGlobeAsia,
  faImage,
  faInfo,
  faInfoCircle,
  faMap,
  faPenAlt,
  faPlus,
  faPrint,
  faQuestion,
  faQuestionCircle,
  faSearch,
  faSignInAlt,
  faShippingFast,
  faSpinner,
  faStar,
  faTags,
  faTimes,
  faTrashAlt,
  faTruck,
  faUser,
  faWallet,
  faWarehouse
])

Vue.component('font-awesome-icon', FontAwesomeIcon)
